### ISSUE TITLE
Links from ./foo/bar.md to ../baz/foo-bar.md issues 

### ISSUE THREAD

**Issue by joesustaric** [hunyadi/md2conf#19]
Hi there, thanks for writing this project - its proving super helpful for one of my use cases.

I've noticed something that seems to be throwing consistent exceptions. (haven't had time to dig in yet but thought I'd log this one in case)

in a markdown file in a location like `./foo/bar.md` that has a relative link to `[link](../blah/something.md)` It appears that the code throws this exception - Even though the relative link is valid for that file location.
```
File "/Users/user/src/work/md2conf/md2conf/converter.py", line 260, in _transform_link
    raise DocumentError(f"relative URL points to outside base path: {url}")
md2conf.converter.DocumentError: relative URL points to outside base path: ../blah/something.md
```

Will attempt to debug this soon and may submit a PR if I figure it out. 

Thanks!

**Comment by hunyadi** [comment]
This is an intentional (security) feature to prevent inadvertently injecting potentially harmful or sensitive content into a document. `md2conf` defines a *base path*, and all relative paths must resolve to a path that is identical to or a descendant of the base path. For example, assuming the base path is `/root/base/`, documents can reference `sub1/doc1.md` (resolves to resource in child folder `/root/base/sub1/doc1.md`) or `doc2.md` (resolves to sibling entry `/root/base/doc2.md`) but not `../sub3/doc3.md`, which would resolve to `/root/sub3/doc3.md`, which is no longer inside `/root/base/`.

Currently, the *base path* is tied to the document. However, I could imagine a feature improvement in which you can configure *base path*, and relax where references can point to.

**Comment by joesustaric** [comment]
Ok I see. Understood.

In my use case it would be great if there could be a non default switch to bypass this or just allow and relative link from the base dir.

**Comment by hunyadi** [comment]
A new command line configuration option `--ignore-invalid-url` has been added to prevent exceptions when invalid links are encountered. You will still need to export a full document tree to ensure that cross-referencing relative links are resolved (e.g. you need to export document *A* to ensure that links found in document *B* that point to document *A* are resolved).

**Comment by joesustaric** [comment]
Thanks very much!
