### ISSUE TITLE
Relative links to gitlab files

### ISSUE THREAD

**Issue by felixschilling** [hunyadi/md2conf#20]
Hi, 

I have some Gitlab Markdown documents that I want to export to Confluence. Everything is working smooth except relative links to files in gitlab. 

Example: 
`- [.gitlab-ci.yml](.gitlab-ci.yml)`

It returns the following error:
`Processing README.md
2023-11-06 11:35:02,249 - INFO - _synchronize_page [87] - Synchronizing page: README.md
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/site-packages/md2conf/__main__.py", line 85, in <module>
    Application(api, ConfluenceDocumentOptions(args.generated_by)).synchronize(
  File "/usr/local/lib/python3.12/site-packages/md2conf/application.py", line 34, in synchronize
    self.synchronize_page(path)
  File "/usr/local/lib/python3.12/site-packages/md2conf/application.py", line 41, in synchronize_page
    self._synchronize_page(page_path, dict())
  File "/usr/local/lib/python3.12/site-packages/md2conf/application.py", line 88, in _synchronize_page
    document = ConfluenceDocument(page_path, self.options, page_metadata)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/md2conf/converter.py", line 531, in __init__
    converter.visit(self.root)
  File "/usr/local/lib/python3.12/site-packages/md2conf/converter.py", line 198, in visit
    self.visit(source)
  File "/usr/local/lib/python3.12/site-packages/md2conf/converter.py", line 194, in visit
    target = self.transform(source)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/md2conf/converter.py", line 420, in transform
    return self._transform_link(child)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/md2conf/converter.py", line 260, in _transform_link
    raise DocumentError(f"unable to find matching page for URL: {url}")
md2conf.converter.DocumentError: unable to find matching page for URL: .gitlab-ci.yml`

Is there an option or possibility to add a feature, that relative links will be converted to text, so the pipeline will not fail? Or does someone have a better idea?

Thanks a lot!

**Comment by hunyadi** [comment]
Today, relative links to resources that are not exported trigger an error because there would be no matching document in Confluence for the linked entity when the document tree is published as a series of wiki pages. However, there could be a configuration option or command-line switch to suppress unmatched link errors, and emit a warning message instead.

**Comment by hunyadi** [comment]
A new configuration option `--ignore-invalid-url` has been added to skip relative URLs that point to locations not synchronized with the document or document tree. These will still show up as links in Confluence but will not navigate to another place (as if they were `<a href="#">...</a>`). A warning message will be emitted when these invalid links are encountered.

**Comment by amorphina** [comment]
Hey Levente,

Sorry to reopen this but would it be better to have an argument where you can specify a base URL for all relative links.
If for example we have a `--base-url=http://mywebsite.com/something/` and a link in the markdown such as `[.gitlab-ci.yml](.gitlab-ci.yml)` the resulting link should be something like http://mywebsite.com/something/.gitlab-ci.yml

**Comment by hunyadi** [comment]
*md2conf* already has a concept of *base URL* so we will need to clarify semantics. Currently, base URL means the root URL of a document tree, and md2conf maintains a catalog mapping (relative) URLs to Markdown documents. This is how *md2conf* makes sure that every document in the tree has a corresponding exported document in Confluence. If it were not for this catalog, there could be broken links.

On the other hand, I understand that you are asking for a different type of *base URL*, which would only apply to links that don't map as per the URL to Markdown catalog that *md2conf* maintains. Instead of ignoring these URLs, you would like them to be prefixed with a configured URL prefix to turn them into absolute URLs. They would appear as absolute URLs in Confluence wiki pages.
