### ISSUE TITLE
Add custom headers and web ui links

### ISSUE THREAD

**Issue by pgsantos-pt** [hunyadi/md2conf#57]
I have a very specific use case where the API token does not suffice. Confluence for me sits behind Cloudflare so I need specific headers to be able to make secured requests.
I also have another issue with relative URLs because they are being converted to API endpoint URLs, such as `https://<confluence_domain>/space/<spaceKey>/pages/<id>/<title>`. However, this is not understood by Confluence's Web UI.

I already created these changes and I've followed the information in the contributing page but I can't open the pull request:
```
git push --set-upstream origin custom-headers-web-links
remote: Permission to hunyadi/md2conf.git denied to pgsantos-pt.
fatal: unable to access 'https://github.com/hunyadi/md2conf.git/': The requested URL returned error: 403
```

If you think these features would be candidates for inclusion please advise about what I can do to be able open the pull request. I can also send a patch to you. Otherwise, just let me know you don't want to adopt it and you can close this issue.

**Comment by hunyadi** [comment]
I am definitely interested in taking a look.

You can't push directly to the official repository `hunyadi/md2conf` because you have not been granted write permissions. However, you can create your own fork of `pgsantos-pt/md2conf`, push to that repository, and open a pull request to the original repository `hunyadi/md2conf`. This is how developers contributed to *md2conf* in the past. I am also glad to look at a patchset.

**Comment by pgsantos-pt** [comment]
Hi, pull request created https://github.com/hunyadi/md2conf/pull/58. I did miss the fork, sorry about that. Anyway, left some details in the description. Just let me know what you think!
