### ISSUE TITLE
Unable to set page titles and pages not being set as child

### ISSUE THREAD

**Issue by m-d-greaves** [hunyadi/md2conf#66]
I have testing the tool to publish pages to our Confluence space and it works well for publishing directly; however, the page titles are set to be the same as the file names. Is it possible to set the page titles per file?

I also noticed when publishing a directory which contains an index.md that the other files are not being set as children to this page. 

This is using `python -m md2conf -r 123456789  confluence-pages` where the confluence-pages directory contains index.md and several other files.

**Comment by hunyadi** [comment]
As of today, there are no options to configure how the title of the Confluence target page is set. Several options have been proposed: use the file name, the topmost heading (i.e. the first heading with `#`), or the title assigned in the frontmatter. At the time of writing, newly created pages are always assigned a title based on the source file name.

Looks like the check for `index.md` and `README.md` is missing the path. Currently, `application.py` reads:
```
if "index.md" in files:
    parent_id = read_qualified_id(Path(local_dir) / "index.md")
elif "README.md" in files:
    parent_id = read_qualified_id(Path(local_dir) / "README.md")
```
However, it should likely read as follows because this is how the entries are populated in `files`:
```
if Path(local_dir) / "index.md" in files:
    parent_id = read_qualified_id(Path(local_dir) / "index.md")
elif Path(local_dir) / "README.md" in files:
    parent_id = read_qualified_id(Path(local_dir) / "README.md")
```
I will make this change, thanks for raising awareness.

**Comment by hunyadi** [comment]
New code has been pushed to `master` that looks into Markdown front-matter, and if it finds a `title` field in the front-matter YAML object, it will set that string as the `title` property for the newly published Confluence page. (Otherwise, it uses the file name as before.)

Path look up for `index.md` and `README.md` has been fixed. Initial tests show that these files are now properly found and considered as page parents. If you have the time, can you verify this behavior?

If you encounter any issues after the code updates, feel free to open a new ticket. (I would recommend against re-opening this ticket because it covers two issues. It's best to have each issue report target a specific problem or cover a specific feature request.)
